### ISSUE TITLE
Install via brew

### ISSUE THREAD

**Issue by awead** [hectorcorrea/marcli#2]
```
~ brew search marcli
Error: No formulae or casks found for "marcli"
```

I've done a little work getting formulae into brew, and would be happy to run point on it, if this is possible.

**Comment by kayiwa** [comment]
heh... great minds... okay perhaps not... but was thinking the same @awead https://github.com/kayiwa/brew_marccli

**Comment by kayiwa** [comment]
Looks like Github can do this @awead https://twitter.com/phette23/status/1383120247813640194

**Comment by kayiwa** [comment]
bug fixed. ;-) 
<img width="918" alt="image of brew upgrade" src="https://user-images.githubusercontent.com/685884/115209079-40bf0d80-a0cb-11eb-8b1e-a57326b0817f.png">

**Comment by hectorcorrea** [comment]
This was done by @phette23 via PR https://github.com/Homebrew/homebrew-core/pull/75431. Thanks Eric!
