### ISSUE TITLE
Release tag issue

### ISSUE THREAD

**Issue by sunshineplan** [hectorcorrea/marcli#6]
[Golang blog](https://blog.golang.org/publishing-go-modules#TOC_3.) says: A semantic version has the form vMAJOR.MINOR.PATCH.
So tag should be v1.0.1, not 1.0.1. Otherwise, go.mod will show pseudo-version like "github.com/hectorcorrea/marcli v0.0.0-20201116173935-903994c1d59f", which dependabot can't detect its new version currently.

**Comment by hectorcorrea** [comment]
Thanks for the pointer, the latest release uses the convention that you suggested: https://github.com/hectorcorrea/marcli/releases/tag/v1.1.0
